### ISSUE TITLE
xml data extract only

### ISSUE THREAD

**Issue by deepakkuk** [tamimmirza/Intrusion-Detection-System-using-Deep-Learning#5]
![screenshot from 2018-12-01 15-56-51](https://user-images.githubusercontent.com/33250220/49327053-c638d600-f581-11e8-91b3-ca5b6c3b2926.png)
When i run xml extract.py file on terminal show this no npy file saved.

**Comment by tamimmirza** [comment]
You have to run `Data_Extraction_Revised.py` which converts that into .npy file

Because I already gave you the xml data so you don't need to run `xml extract.py` on it

**Comment by deepakkuk** [comment]
I run Data_Extraction_Revised.py  but it show error in split test form
![screenshot from 2018-12-01 17-28-56](https://user-images.githubusercontent.com/33250220/49327978-a8be3900-f58e-11e8-98c9-a13d7ee9f386.png)

**Comment by tamimmirza** [comment]
Try excluding the last few few files after jun16 see if that works

**Comment by tamimmirza** [comment]
No that is actually the correct output.
You should see that there is a folder with numpy arrays. Thats all you need.

Ignore the error
