### ISSUE TITLE
one file can't convert .npy file show error in opening

### ISSUE THREAD

**Issue by deepakkuk** [tamimmirza/Intrusion-Detection-System-using-Deep-Learning#6]
TestbedThuJun17-1Flows.xml not open
![image](https://user-images.githubusercontent.com/33250220/49339724-010f3c80-f65c-11e8-9b1e-96fbb9f0ea81.png)

**Comment by tamimmirza** [comment]
Ignore that file, it is corrupted
We found out that some files in ISCX 2012 dataset were corrupted therefore we exempted them from the project
