### ISSUE TITLE
Labels missing from extracted xml

### ISSUE THREAD

**Issue by psychogyiokostas** [tamimmirza/Intrusion-Detection-System-using-Deep-Learning#7]
Hello,

I have followed the steps you mention to extract a labeled flow file using the ISCX 2012 data set.

Using as input to the ISCX FlowMeter the file: testbed-12jun.pcap i get as output the flow file .

The issue here is that the output file is not labeled, unlike the xml outputs they provide in:

http://205.174.165.80/CICDataset/ISCX-IDS-2012/

I can use the xml outputs they have with your notebook (all good), but i am concerned about how to obtain the labeled xml file in first place.

I start experimenting with TShark (instead of ISCX FlowMeter) now to see if i can get the labeled file.

Any advice on why i can't get a labeled output?

Thank you in advance.

**Comment by tamimmirza** [comment]
Hi

I am afraid that I received my ISCX 2012 dataset (which was already
labeled) from my project advisor who was already performing his own
research on the dataset for his Ph.D.

At the time of me and my colleagues starting out with the project, we did
not have access to download the dataset from the CIC official website which
was odd considering the nature of the dataset being only used for research
and not for any other purpose. They recently changed that model and now the
dataset can be downloaded easily.

Mind you, the dataset that you possess might have undergone some changes as
well as the flowmeter programs you may have used to get the XML formats. So
it is pretty much safe to say that the dataset I used and the one you are
using are different in one way or another.

Unfortunately, I do not possess my original dataset of the ISCX 2012 so on
that note you may either have to search for the labeled version online or
to label it yourself which I would not recommend.

I wish you good luck

**Comment by psychogyiokostas** [comment]
So the raw pcap files they provide in:

http://205.174.165.80/CICDataset/ISCX-IDS-2012/Dataset/

are not labeled, and i would either have to label them myself or search/contact the authors to access the labeled version of the raw pcap files in the link above?

Thank you for your fast response!

**Comment by tamimmirza** [comment]
Yeah that's the idea
Sorry I couldn't be more help

**Comment by psychogyiokostas** [comment]
You helped me more than you think :)

Thanks again

**Comment by psychogyiokostas** [comment]
@tamimmirza Is it possible for the labels 0/1 to exist in some format inside a pcap file? Or they can only be provided separately in a say ground_truth.csv file?

**Comment by psychogyiokostas** [comment]
solved. there is no such things such as labels in pcap files. They can only be provided by the authors, or download directly their pre-processed flows including labels (which they have added manually)
