### ISSUE TITLE
A question about Data_Extractin_Revised.py

### ISSUE THREAD

**Issue by soccerwhy** [tamimmirza/Intrusion-Detection-System-using-Deep-Learning#8]
Hello,man：
         Best wishes from China!!
         When you transfer the dataset to .npy format on the Data_Extractin_Revised.py, only destinationPayloadASUTF can affect the result(normal or abnormal). I want to know the reason and why the Parameter actual is 7500. Could you give me an answer? Appreciate very much!!!

**Comment by psychogyiokostas** [comment]
That's a nice question! 
I would like to know as well please.

**Comment by tamimmirza** [comment]
> Hello,man：
> Best wishes from China!!
> When you transfer the dataset to .npy format on the Data_Extractin_Revised.py, only destinationPayloadASUTF can affect the result(normal or abnormal). I want to know the reason and why the Parameter actual is 7500. Could you give me an answer? Appreciate very much!!!

It is because of the custom image format. They are set to 50x50x3 (50 height, 50 width, 3 dimensions).

Convolutional neural network require minimum image size of 48x48x3 as input data.
